name: release-action
on: [ push ]
jobs:
  release-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: access secret
        env:
          MC_REPOSITORY_URL: ${{secrets.MC_REPOSITORY_URL}}
        run: echo "$MC_REPOSITORY_URL"
#      - name: Build with Gradle
#        run: ./gradlew clean build